title: Zhao Jiangbo's Homepage
page-top-title: Zhao Jiangbo
top-section-bg-text: Computing theroy  Graph theroy
home-subtitle: Zhao Jiangbo（赵江波）
copyright-text: '&copy; Li Sen 2023-2026. All Rights Reserved.'
